### ISSUE TITLE
missing parameter in config/config.yaml

### ISSUE THREAD

**Issue by cheeseJelly** [TAMS-Group/efficient-motion-reconstruction#2]
When I run example `rosrun tams_human_motion tams_human_motion `rospack find tams_human_motion`/config/config.yaml `rospack find tams_human_motion`/data/mediapipe/cartwheel.yaml `rospack find tams_human_motion`/data/mediapipe/cartwheel.txt`, the following error occurs:

> [path]/src/efficient-motion-reconstruction/tams_human_motion/scripts/src/configuration.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  c = yaml.load(open(filename))
point count 33
loading data file [path]//src/efficient-motion-reconstruction/tams_human_motion/data/mediapipe/backflip.txt
Traceback (most recent call last):
  File "[path]//src/efficient-motion-reconstruction/tams_human_motion/scripts/tams_human_motion", line 40, in <module>
    dataset = Dataset(path=datafile, time_step=1.0 / config["recording"]["fps"])
  File "/[path]/src/efficient-motion-reconstruction/tams_human_motion/scripts/src/dataset.py", line 39, in __init__
    if config["network"]["YZswitch"]:
KeyError: 'YZswitch'

I found there are no YZswitch in config.yaml
config.yaml
![Screenshot from 2024-04-16 14-10-46](https://github.com/TAMS-Group/efficient-motion-reconstruction/assets/6104524/2cbe64bb-b5c9-4184-9651-780f17d5a4b1)

But it is existed in config_metrabs.yaml
![Screenshot from 2024-04-16 14-10-37](https://github.com/TAMS-Group/efficient-motion-reconstruction/assets/6104524/336e6781-d5ca-4ad8-82a8-5d5a5956985d)

I am writing to raise awareness of this issue. 
Please edit the config file. Thanks for good project!

**Comment by WanMRRusli** [comment]
I am pretty new to this. However, this seems to be a good work. The installation instruction is not quite clear to me. @cheeseJelly do you know or are you okay to share regarding the installation procedure?
